# Generated by Django 5.0 on 2024-03-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PApp', '0002_remove_project_photo_project_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
